import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as s3 from 'aws-cdk-lib/aws-s3';

export interface PollyStackProps {
  userPool: cognito.UserPool;
  identityPool: cognito.CfnIdentityPool;
}

export class PollyStack extends Construct {
  public readonly pollyClient: any; // This is a placeholder as CDK doesn't have a direct Polly construct
  public readonly audioFilesBucket: s3.Bucket;

  constructor(scope: Construct, id: string, props: PollyStackProps) {
    super(scope, id);

    // Create an S3 bucket to store the audio files generated by Polly
    this.audioFilesBucket = new s3.Bucket(this, 'PollyAudioBucket', {
      removalPolicy: cdk.RemovalPolicy.DESTROY, // For development only, use RETAIN for production
      autoDeleteObjects: true, // For development only
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      cors: [
        {
          allowedMethods: [s3.HttpMethods.GET],
          allowedOrigins: ['*'], // Restrict to your CloudFront domain in production
          allowedHeaders: ['*'],
        },
      ],
    });

    // Grant authenticated users access to Polly and the S3 bucket
    const authenticatedRole = iam.Role.fromRoleArn(
      this,
      'ImportedAuthRole',
      cdk.Fn.importValue('AuthenticatedRoleArn')
    );

    // Add Polly permissions to the authenticated role
    authenticatedRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          'polly:SynthesizeSpeech',
          'polly:StartSpeechSynthesisTask',
          'polly:GetSpeechSynthesisTask',
        ],
        resources: ['*'],
      })
    );

    // Grant read/write access to the S3 bucket
    this.audioFilesBucket.grantReadWrite(authenticatedRole);

    // Output the bucket name
    new cdk.CfnOutput(this, 'PollyAudioBucketName', {
      value: this.audioFilesBucket.bucketName,
    });
  }
}